### ISSUE TITLE
Film releaseDate crash

### ISSUE THREAD

**Issue by goertzenator** [shopgun/graphql-erlang-tutorial#15]
The query...
```
query asdsdf {
  allFilms {
    director
    title
    releaseDate
  }
}
```

... produces a failing result...

```
{
  "data": {
    "allFilms": [
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "errors": [
    {
      "path": [
        "releaseDate",
        0,
        "allFilms",
        "asdsdf"
      ],
      "reason": "{coerce_crash,<<\"DateTime\">>,<<\"1977-05-25\">>,{error,function_clause}}"
    },

<snip>
 ```

PS, I am extremely impressed with this app and documentation!

**Comment by jlouis** [comment]
My bad. If you want a stab at a PR change the type in sw.schema to String.
It isn't ISO8601. Or alter the db code to datetime parse the field and roll
a new FALLBACK.BUP.

I'll fix it tomorrow in any case.

**Comment by jlouis** [comment]
Should be fixed now. Thank you for the bug report and the kind words!
