### ISSUE TITLE
sw_core_mutation module is missing

### ISSUE THREAD

**Issue by benoitc** [shopgun/graphql-erlang-tutorial#16]
not sure it's expected but looking at the mapping map mutations are handled via the module `sw_core__mutation` which is missing in ghe source.

**Comment by jlouis** [comment]
It is expected for now. That part of the tutorial has not been written yet, so I just lazily carved out the name of the module. Once I start documenting mutations (next up on the list) then the module will come into existence.

**Comment by jlouis** [comment]
Tracked in #17

**Comment by jlouis** [comment]
There is now a `sw_core_mutation` module and part of the mutations are written. We still need to handle *Starship* as a type, but I've decided to push what I have now and go for the Starship next up.
