### ISSUE TITLE
Relay Modern specification

### ISSUE THREAD

**Issue by benbro** [shopgun/graphql-erlang-tutorial#24]
The Relay term is being used before it was defined. The reader still doesn't know what it is.

https://shopgun.github.io/graphql-erlang-tutorial/#_first_query
> In accordance with the rules of **Relay Modern** GraphQL conventions, we will load this Planet via the Object Identification conventions:

https://github.com/shopgun/graphql-erlang-tutorial/blob/master/doc/schema.asciidoc#the-node-interface
> The **Relay Modern** specification contains a number of standards for how to implement different parts of the GraphQL schema.

**Comment by jlouis** [comment]
`Object Identification conventions` is another term which @benbro mentioned on IRC.
