### ISSUE TITLE
Apollo project definition

### ISSUE THREAD

**Issue by benbro** [shopgun/graphql-erlang-tutorial#26]
Missing explanation about the Apollo project.

https://github.com/shopgun/graphql-erlang-tutorial/blob/master/doc/schema.asciidoc#the-node-interface

> The Erlang version of GraphQL allows a certain extension by the Apollo people.

**Comment by jlouis** [comment]
Yes, a link and so on would be nice, I agree!

**Comment by jlouis** [comment]
Thank you so much for your contribution! I  have made fixes for all the issues you currently have open, but I'll write to you in this one and thank you for helping improving the tutorial. I think I managed to nail them all by rewriting the text such that it should be easier to read. I've also added some forward references where applicable.
