### ISSUE TITLE
Error querying starships 

### ISSUE THREAD

**Issue by davecaos** [shopgun/graphql-erlang-tutorial#40]
I can't query `jedi starfighter` :rocket: starship in the graphql-erlang-tutorial 
```javascript
      {
        "id": "U3RhcnNoaXA6NDg=",
        "name": "Jedi starfighter"
      }
```

this is the example with GraphiQL  [http://localhost:17290/?query=queryy...](http://localhost:17290/?query=query%20StarShipQuery(%24id%20%3A%20ID!)%20%7B%0A%20%20%20%20node(id%3A%20%24id)%20%7B%0A%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20...%20on%20Starship%20%7B%0A%20%20%20%20%20%20%20%20%20%20model%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0A%23%7B%0A%23%20%20%20%22id%22%3A%20%22U3RhcnNoaXA6NDg%3D%22%2C%0A%23%20%20%20%22name%22%3A%20%22Jedi%20starfighter%22%0A%23%7D%0A%20%20%20%20%20%20%0A%23(sw%40127.0.0.1)1%3E%20sw_core_id%3Adecode(%3C%3C%22U3RhcnNoaXA6NDg%3D%22%3E%3E).%20%0A%23%7Bok%2C%7B%27Starship%27%2C48%7D%7D%20%0A%0A%0Aquery%20StarShipQueryHardcoded%7B%0A%20%20%20%20node(id%3A%20%22U3RhcnNoaXA6NDg%3D%22)%20%7B%0A%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20...%20on%20Starship%20%7B%0A%20%20%20%20%20%20%20%20%20%20model%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D&operationName=StarShipQuery&variables=%7B%0A%20%20%22id%22%3A%20%22U3RhcnNoaXA6NDg%3D%22%0A%7D)
and I had a this error  in the output when I ran both examples:
```javascript
{
  "data": {
    "node": null
  },
  "errors": [
    {
      "path": [
        "node",
        "StarShipQuery"
      ],
      "reason": "{no_exists,'Transport'}"
    }
  ]
}
```
I had this error even I didn't run any mutation before over the graphql server.

**Comment by jlouis** [comment]
Yes, this was a bug indeed. Fixed in 86cabaf .. check if it works for you (the commit message should explain the problem).

**Comment by jlouis** [comment]
(Edit of comment to right commit ID)
