### ISSUE TITLE
Why not Cowboy 2.x?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [shopgun/graphql-erlang-tutorial#58]
Could the tutorial be updated to use cowboy 2.x?

**Comment by jlouis** [comment]
It should be! I wrote it when Cowboy 2.x was quite new and I wanted a stable system to work against. But given time has passed, we should definitely make the upgrade.

The Jun2018 specification is bound to make changes to the tutorial anyway, and this is an update which ought to piggy-back on the update with the specification.

**Comment by CharlesIrvineKC** [comment]
Thanks for the update!!
